# Generated by Django 4.2.6 on 2023-10-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=220)),
                ('nationality', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status_author', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('publication_date', models.DateField(verbose_name='Fecha de publicación')),
                ('creation_date_book', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('author_id', models.ManyToManyField(to='app_book.author')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['id'],
            },
        ),
    ]
