# Generated by Django 4.2.6 on 2023-10-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=220, verbose_name='Apellidos')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nacionalidad')),
                ('description_author', models.TextField(verbose_name='Bio')),
                ('status_author', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('publication_date', models.DateField(verbose_name='Fecha de publicación')),
                ('description_book', models.TextField(verbose_name='Descripción')),
                ('creation_date_book', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('front_page', models.ImageField(upload_to='')),
                ('author_id', models.ManyToManyField(to='app_book.author')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['id'],
            },
        ),
    ]
